# Generated by Django 4.2.23 on 2025-07-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LTISession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('canvas_user_id', models.CharField(max_length=255)),
                ('canvas_course_id', models.CharField(blank=True, max_length=255)),
                ('canvas_roles', models.JSONField(default=list)),
                ('canvas_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LTIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('key_set_url', models.URLField()),
                ('auth_token_url', models.URLField()),
                ('auth_login_url', models.URLField()),
                ('deployment_id', models.CharField(blank=True, max_length=255)),
                ('private_key', models.TextField()),
            ],
            options={
                'unique_together': {('issuer', 'client_id')},
            },
        ),
    ]
